ComputeCanada/software-stack-custom

bin/computecanada/diskusage_breakdown
bin/computecanada/diskusage_report

This add a section in the bottom of `diskusage_report` that is only displayed if the databases exist on disk.

Modifying diskusage_report to add the info from `duc`

---

bin/computecanada/diskusage_report

Siku uses GPFS for shared FS, which doesn't allow users to query their quota like `lfs quota` does.
Instead a cron-job dumps the quota information into files, which are then used by `diskusage_report` to read the data.
This PR fixes two issues:
1) When a quota is exceeded, the column that contains the remaining "grace period" will change from `none` to `7 days`, `36 hours`, `1 hour` and finally to `expired`.  The extra space-char causes the parsing of the file to fail, resulting in an error message during the grace period.
The fix is to include a `sed` into the pipe that replaces that space with an underscore ahead of `(days|hours?)`.
2) The reporting of user-quota on /project is now enabled on Siku.

Mods for Siku

---

modules/StdEnv/2020.lua

This way it's possible to do "module load intel/2021.2.0" and have
it autoload openmpi/4.1.1 instead of saying
Inactive Modules:
1) openmpi/4.0.3
The defaults are set in the module directories using .modulerc.lua
files and unchanged from what is in StdEnv/2020.lua before this
change (e.g. version 2020.1.217 for intel/imkl)

Load default versions of modules in StdEnv/2020

---

modules/singularity/3.5.lua
modules/singularity/3.6.lua
modules/singularity/3.7.lua

Reverts ComputeCanada/software-stack-custom#15
After testing, the above does not work. If the folder does not exist, singularity reverts back to $HOME/.singularity/cache. Setting SINGULARITY_CACHEDIR to $SCRATCH would create $SCRATCH/cache, which is a risk of conflict with users' files in $SCRATCH

Revert "added code to set SINGULARITY_CACHEDIR"

---

bin/virtualenv

It was loading the one from gentoo/2019, an old leftover from
when I compiled Python with Gentoo instead of EasyBuild.

Show error message for virtualenv with StdEnv/2020.

---

bin/scp
bin/sftp

Can anyone think of a reason *not* to shadow the gentoo-provided scp/sftp to use the OS versions, just like we do for `ssh` ?

added symlinks for scp and sftp to use the os-provided versions

---

modules/gentoo/2020.lua.core

I believe this fixes https://github.com/ComputeCanada/software-stack/issues/92
Paul, can you test by manually unsetting `PAGER` in your use case ?

unset PAGER in gentoo as this is not needed and not POSIX

---

bin/ld.gold

This option is necessary to workaround a Lustre bug visible only on Narval.
According to strace we see this:
mmap(NULL, 309576, PROT_READ|PROT_WRITE, MAP_SHARED, 18, 0) = 0x7f10e68b5000
--- SIGBUS {si_signo=SIGBUS, si_code=BUS_ADRERR, si_addr=0x7f10e68fbd88} ---
the address 0x7f10e68fbd88 is within the mmap'ed range 0x7f10e68b5000 to 0x7f10e68b5000+309576
so this should not SIGBUS
Since it will take some time to fix the bug on Lustre's end I feel the wrapper is
the best solution for the near future. There's a bug report with a very similar
error but that's supposed to be fixed so not sure what is happening here:
https://jira.whamcloud.com/browse/LU-13588

Add --no-mmap-output-file to ld.gold on Narval

---

modules/CCconfig.lua

This avoids issues for ls in $HOME with symbolic links when scratch
is down.
By default symbolic links that point to an invalid location are
red on black, and valid ones are cyan.
This change makes the invalid ones cyan too, and avoids multiple
syscalls for plain "ls --color=auto".

Add or=00 to LS_COLORS

---

bin/computecanada/diskusage_report
sources/install-lmod.sh

This should be one more step toward fixing 
https://github.com/ComputeCanada/software-stack/issues/110
Once tested a bit more widely, Robert will released Lmod 8.8 to address that. 
Note that this should not be deployed to production without proper testing on Niagara.

bump Lmod to 8.7.4 to support dynamic modulepaths in caches

---

.gitignore
python/site-packages/_manylinux.py

Ignore any `manylinux_x_y` wheels! 
With PEP600 (https://peps.python.org/pep-0600/) there simply too many
combinations. The `manylinux_compatible` function takes care to discard
any manylinux_x_y candidate.
Previous version of pip refused to install manylinux wheels but this solve an issue where a recent pip (22.2) would still install a
manylinux_x_y wheel.
With our system `_manylinux.py`, it had precedence over the `no-manylinux` package, hence one could still install such packages:
```bash
(16879) ~ $ pip install no-manylinux
Successfully installed no-manylinux-3.0.0
(16879) ~ $ pip install orjson-3.7.8-cp38-cp38-manylinux_2_28_x86_64.whl 
Successfully installed orjson-3.7.8
```
With this fix:
```bash
(1260) ~ $ pip install orjson-3.7.8-cp38-cp38-manylinux_2_28_x86_64.whl 
ERROR: …
```

No manylinux! Point final!

---

modules/apptainer/1.0.lua
modules/singularity/3.7.lua
modules/singularity/3.8.lua

The unsquashfs binary in Gentoo is incompatible with Apptainer < 1.1 and Singularity 3.7/3.8. Force the use of /usr/sbin/unsquashfs via a symbolic link in
/cvmfs/soft.computecanada.ca/custom/software/apptainer/bin and adding that to PATH.
This didn't use to be necessary since Singularity/Apptainer rejected the Gentoo unsquashfs because it did not support xattr. Now that it does support xattr (for compatibility with 1.1) it runs into a GLIBC_PRIVATE symbol issue with older versions on CentOS 7.

Singularity/Apptainer: add custom bin directory to PATH

---

bin/computecanada/diskusage_explorer

La précédente version était basée sur les exemples qui n'utilisaient que `/project`. Et encore, les exemples de la documentation ne fonctionnaient pas à cause de l'expression régulière qui exigeait un `/` après le GID... Bref, voilà une nouvelle version : 
* Nouveaux arguments `-h` et `--help` avec plus d'information
* Compatible avec les chemins dans `/home` et `/scratch`, en plus de `/project/<gid>`
* Compatible avec des paths contenant des espaces

Du explorer/fix parent dir

---

bin/computecanada/diskusage_explorer

Bien que la [page de documentation](https://docs.alliancecan.ca/wiki/Diskusage_Explorer) ne le mentionnait pas, la sortie de `diskusage_report` mentionne la possibilité d'appeler le script avec un chemin vers `/nearline`. Les fichiers SQLite étaient effectivement présents sur Béluga. Un correctif a été implémenté pour que ce soit aussi le cas sur Narval. Ainsi, `diskusage_explorer` devrait pouvoir fonctionner avec des chemins dans `/nearline` et cette version permet de le faire.

Bringing back support for /nearline

---

modules/CCconfig.lua

TMPDIR set to SLURM_TMPDIR has issues with recursive sbatch invocations, since Slurm complains about it not existing in inner jobs and CCconfig will not adjust it then. As in 2017 the only reason for defining TMPDIR was to avoid filling up / instantly using /tmp, but since then /tmp has changed to a private tmpfs mount set up by a SPANK plugin, so we can just leave TMPDIR untouched (as was the consensus in 2017 otherwise).
Slurm doesn't complain about LOCAL_SCRATCH but it still needs to be set correctly in a recursive job and not be inherited as an invalid directory name.

CCconfig: don't define TMPDIR, fix LOCAL_SCRATCH

---

modules/apptainer-suid/1.1.lua

Due to https://www.cvedetails.com/cve/CVE-2023-30549/ we will need to disable all older suid singularity/apptainer modules and use this one instead.

Add apptainer-suid/1.1 module

---

modules/gentoo/2023.lua.core

Remove $EBROOTGENTOO/sbin from module path.

---

modules/gentoo/2023.lua.core

This uses
`/cvmfs/soft.computecanada.ca/easybuild/modules/2023/x86-64-v3/Compiler/gcccore:/cvmfs/soft.computecanada.ca/easybuild/modules/2023/x86-64-v3/Core`
instead of
`/cvmfs/soft.computecanada.ca/easybuild/modules/2023/avx2/Core:/cvmfs/soft.computecanada.ca/easybuild/modules/2023/Core` 
in `MODULEPATH` for `avx2` and `v4` for `avx512`; the `Core` for v4 will be a symlink to `v3`.
This makes the path consistent with `EBROOTGENTOO`
(`/cvmfs/soft.computecanada/gentoo/2023/x86-64-v3/usr`) but keeps `avx2` and `avx512` names user facing for backwards compatibility.

Use x86-64-v{3,4} in path names.

---

modules/gentoo/.modulerc.lua

So if anyone does "module load gentoo" they won't be surprised when 2023 is published.

Set 2020 as default for gentoo.

---

modules/StdEnv/2016.4.lua
modules/StdEnv/2018.3.lua

This works with https://github.com/ComputeCanada/software-stack-config/pull/61
The only caveat is that the new MODULERCFILE does not apply until the module is loaded. That means if a user is loading StdEnv/2016.4 or StdEnv/2018.3 and is relying on the default versions, they may get more recent versions.

add custom MODULERCFILE when loading the old StdEnv

---

modules/StdEnv/2023.lua

Loads `gcc/12.3`, `openmpi/4.1.5`, `flexiblas/3.3.1` and either `imkl` or `blis` depending on Intel or AMD

Proposed new StdEnv/2023

---

bin/cmake

The lack of cmake3 in Gentoo confuses this logic. I could instead point it to the Gentoo cmake command, but this is simpler.

Switch cmake wrapper for 2023 to module for 3.27.7 instead of Gentoo

---

modules/gentoo/2023.lua.core

always, instead of the symlink to x86-64-v3 for x86-64-v4.

Use /cvmfs/soft.computecanada.ca/easybuild/modules/2023/x86-64-v3/Core

---

modules/StdEnv/2020.lua

StdEnv/2020 with Intel and AVX512 doesn't work on AMD Genoa

---

.gitignore
modules/apptainer-suid/1.1.lua
software/apptainer/bin/apptainer
software/apptainer/bin/singularity
software/apptainer/bin/unsquashfs

This uses the existing structure of
`/cvmfs/soft.computecanada.ca/custom/software/apptainer/bin` to create a wrapper file there and adjusts the module to the same thing for environment variables as plain apptainer

Port use of APPTAINER_* environment variables to apptainer-suid

---

modules/StdEnv/2023.lua

This is needed since e119f1bad4 otherwise using avx512 / x86-64-v4 the modules under Core aren't visible for spider since it still looked under x86-64-v4

Always use x86-64-v3/Core for Core subdirectory in spider

---

modules/nixpkgs/16.09.lua.core

I believe this fixes https://github.com/ComputeCanada/software-stack/issues/152 and possibly also https://github.com/ComputeCanada/software-stack/issues/153 as well

do not add nixpkgs based paths to MODULEPATH when using spider, regardless of CPU type

---

modules/StdEnv/2023.lua
modules/gentoo/2023.lua

And spider will no longer expand modulepath for them. Tested with `module --force purge` and setting MODULEPATH to the git checkout directory.

Refuse to load StdEnv/2023 and gentoo/2023 for sse3/avx

---

bin/computecanada/diskusage_report.py

Print an error message instead of throwing a stack-trace

throw error message if no supported fs_type detected

---

bin/run_mcr_binary.sh

To make this wrapper script compatible with modules outside of the Nix collection, it only needs to test if the interpreter is in `/cvmfs/soft.computecanada.ca/*`.
The syntax of `*"string"*` is a simple pattern to be matched, where the `string` has to be anywhere in the other string before the `!=` operator.
- https://stackoverflow.com/questions/229551/how-to-check-if-a-string-contains-a-substring-in-bash

Only test if the interpreter is from CVMFS
